[project]
name = "the-code-rx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair>=5.5.0",
    "numpy>=2.2.3",
    "pandas>=2.2.3",
    "quarto>=0.1.0",
    "scipy>=1.15.2",
]
